language: python
sudo: no
python:
  - 2.7
install:
  - pip install -r requirements.pip
  - pip install -r test_requirements.pip
script:
  - DUMMY_SEARCH=y coverage run --source="." manage.py test
after_success:
  coveralls
